name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: SwiftyLab/setup-swift@latest
    - uses: actions/checkout@v4
    - run: swift build
    - run: swift test
